#配置文件版本，勿动！！！
version: 1
#数据库存储方式，群组服选择Mysql
#mysql或db，默认db
Database: db
#Mysql设置，上面填了db的跳过这项
Mysql:
  host: 127.0.0.1
  port: 3306
  database: Dreamyhk
  user: mcyzj
  passwd: '123456'
  ssl: false
#设置命令，必须英文
command:
  #主命令名称
  main: "chat"
  #以下内容填写"null"关闭
  #聊天切换快捷指令
  fast: "c"
  #返回公共聊天快捷指令
  back: "b"
#群聊设置
channel:
  #默认群聊最大人数
  maxPlayer: 20
#设置发言格式
msg:
  #公共频道发言格式
  #{player} 为玩家名称 {msg}为玩家发言内容
  all: "{player}: {msg}"
  #群聊内发言格式
  #{channel_name} 为群聊名称 {channel_power} 为群内的权限
  chat: "[{channel_name}|{channel_power}]{player}: {msg}"